name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploying Files
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            .env
            storage/*.sqlite
            tests/
            phpunit.xml
            .editorconfig
            .styleci.yml